{%- if cookiecutter.python_test_framework == 'pytest' %}
[tool.pytest.ini_options]
addopts = "--cov-report term --cov={{ cookiecutter.python_package_name }}"

{%- endif %}
[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
force_alphabetical_sort = true
force_single_line = true
lines_after_imports = 2
line_length = 88

[tool.flakeheaven]
format="grouped"
max_line_length=88
show_source=true
max-complexity=25

[tool.flakeheaven.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]
"flake8-*" = ["+*"]

[tool.flake8]
format="grouped"
max-line-length=88
show_source=true
max-complexity=25

[tool.plone-code-analysis]
paths = "src/{{ cookiecutter.python_package_name }}/setup.py src/{{ cookiecutter.python_package_name }}/src/ scripts/"
paths_pyroma = "src/{{ cookiecutter.python_package_name }}"
